namespace rolling.dice.fun.Data
{
    /// <summary>
    /// User statistics details
    /// </summary>
    public class StatsModel
    {
        /// <summary>
        /// total entropy size generated by all users
        /// </summary>
        public int TotalSize { get; set; }
        /// <summary>
        /// user entropy size
        /// </summary>
        public int UserSize { get; set; }
        /// <summary>
        /// entropy size in percent
        /// </summary>
        public int UserPrc { get { return (int)(100 * (float)UserSize / (float)TotalSize); } }
    }
}
